### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by by-theo** [zephraph/webview#63]
Error when running

`deno run https://raw.githubusercontent.com/zephraph/webview/refs/heads/main/examples/simple.ts`

<img width="1228" alt="Screenshot 2024-09-26 at 03 12 49" src="https://github.com/user-attachments/assets/90224cbf-5c52-4133-a6ee-6404f5a045ea">

Hardware:
MacBook Air M2

OS:
macOS Sequoia
<img width="392" alt="Screenshot 2024-09-26 at 03 15 59" src="https://github.com/user-attachments/assets/38ed0e30-8c2d-4e3b-88fb-281745355b14">

**Comment by zephraph** [comment]
Thanks for the report! I'll look into this soon.

**Comment by zephraph** [comment]
Could you try `deno run --reload https://raw.githubusercontent.com/zephraph/webview/refs/heads/main/examples/simple.ts`? 

Also what does `deno eval "console.log(Deno.build)"` give you?

**Comment by by-theo** [comment]
Same error for the first one 
<img width="1228" alt="Screenshot 2024-09-26 at 18 19 44" src="https://github.com/user-attachments/assets/7045696a-bfe8-4946-b880-78beddc0c250">

Then this for the second 
<img width="1228" alt="Screenshot 2024-09-26 at 18 20 04" src="https://github.com/user-attachments/assets/a4e73ad7-1242-497a-af12-cee0e5312d41">

**Comment by zephraph** [comment]
Can you try this? https://raw.githubusercontent.com/zephraph/webview/refs/heads/osx-arm64/examples/simple.ts

I think I was missing some logic to pull down the 64bit version of the binary. I also have no idea how it'd be working for me though, I'm on an M1? 🤔

**Comment by by-theo** [comment]
Same error

My deno version is `1.46.3`, I tried with version 2.0 rc as well

I'll uninstall everything and try again

**Comment by by-theo** [comment]
Okay same issue

**Comment by zephraph** [comment]
Let me cut a new release with that fix and we'll see if that does anything.

**Comment by by-theo** [comment]
Let me know when to try

**Comment by zephraph** [comment]
@by-theo it should be out now. Just make sure you run `--reload` with the deno run command. 

```sh
deno run --reload https://raw.githubusercontent.com/zephraph/webview/refs/heads/main/examples/simple.ts
```

**Comment by by-theo** [comment]
Same issue but I'll be testing on another M2 machine today so I'll keep you posted
Might get to test on an M3 as well 🤞🏾

**Comment by by-theo** [comment]
Okay the issue was fixed with your commit from yesterday, I just needed to clear my cache! P.S. it works flawlessly on all of the machines
