### ISSUE TITLE
Exploring a vite plugin

### ISSUE THREAD

**Issue by by-theo** [zephraph/webview#69]
A plugin for running in a vite project

https://github.com/user-attachments/assets/92574f3e-7329-433f-97ad-ea63043f1f2c

I have the basics working but it needs some polish

**Comment by zephraph** [comment]
Very nice! It's been on my todo to put together a fuller example. I was thinking about just pointing the webview at the vite output, but a plugin is a great idea!

**Comment by by-theo** [comment]
I had a similar idea, in dev it would use the localhost url and in prod it would point to the vite output. I'm supposed to be on vacation 😅 but there are tons of things I am going to be trying with it. Expect more demos!

**Comment by zephraph** [comment]
If I can help in anyway, let me know!

**Comment by zephraph** [comment]
Hey @by-theo, I'm going to close this issue, but feel free to open up a show-and-tell discussion: https://github.com/zephraph/webview/discussions/categories/show-and-tell. I still definitely want to hear more about how it's going!
